// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLVBI7DHh8etarOZXxynYFMVJXAwHmUJs',
    appId: '1:234141194565:web:d75af65ce004fb6ccb062c',
    messagingSenderId: '234141194565',
    projectId: 'sales-book-6877c',
    authDomain: 'sales-book-6877c.firebaseapp.com',
    storageBucket: 'sales-book-6877c.firebasestorage.app',
    measurementId: 'G-PJ72ZB6VHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCat1JI-gjXI8LeHrpRp9MhIcyDlGwTMXw',
    appId: '1:234141194565:android:5eb5a95bf03dda92cb062c',
    messagingSenderId: '234141194565',
    projectId: 'sales-book-6877c',
    storageBucket: 'sales-book-6877c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVk-64Eko4imtmHKcY55Egu7_ZeLZukcg',
    appId: '1:234141194565:ios:c65326076cd49dafcb062c',
    messagingSenderId: '234141194565',
    projectId: 'sales-book-6877c',
    storageBucket: 'sales-book-6877c.firebasestorage.app',
    iosBundleId: 'com.example.salesbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVk-64Eko4imtmHKcY55Egu7_ZeLZukcg',
    appId: '1:234141194565:ios:c65326076cd49dafcb062c',
    messagingSenderId: '234141194565',
    projectId: 'sales-book-6877c',
    storageBucket: 'sales-book-6877c.firebasestorage.app',
    iosBundleId: 'com.example.salesbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLVBI7DHh8etarOZXxynYFMVJXAwHmUJs',
    appId: '1:234141194565:web:e860a4c4da40a5fbcb062c',
    messagingSenderId: '234141194565',
    projectId: 'sales-book-6877c',
    authDomain: 'sales-book-6877c.firebaseapp.com',
    storageBucket: 'sales-book-6877c.firebasestorage.app',
    measurementId: 'G-WQ0G33WQ69',
  );
}
